### ISSUE TITLE
Deleted all configs

### ISSUE THREAD

**Issue by ThatsNotAName** [ohitstom/spicetify-easyinstall#20]
**Describe the bug**
Uninstalled spotify and spicetify, deleted all my spotify and spicetify configs, and then left me on the side of the road in a desert with a "could not install" error. Epic

**To Reproduce**
1. Download this
2. Press install
3. Ruin configs
4. Cry about it unhelpfully on github issues

**Expected behavior**
Not delete all my configs and remove my CMD command for spicetify so I have to redo everything from scratch

**Screenshots**
I already deleted this thing out of frustration and I'm prob not gonna download this again

**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser: Brave (chromium)
 - Version: didnt bother

**Additional context**
No this isn't helpful to you fixing the issue I just wanted to cry about it online because I'm angry about it

**Comment by ohitstom** [comment]
You know, there is a verbose for a reason. This is early software and it says in the wiki I'm not responsible for your files. Posting any sort of error information would be helpful. Lots of the time it's due to your country blocking scdn.

Instead of complaining about free software, cope.

**Comment by ohitstom** [comment]
Im closing this unless you want to run the install with verbose enabled and give me proper error information for future users. I appreciate the feedback.

**Comment by ThatsNotAName** [comment]
Preciate you trying to make free software that helps users, my guy. I just wanted somewhere to complain cuz I was frustrated about it. Goodluck!

**Comment by Tetrax-10** [comment]
@ohitstom wasup 👋

**Comment by ohitstom** [comment]
> @ohitstom wasup 👋

what do you want
