### ISSUE TITLE
Ordinal Not Found

### ISSUE THREAD

**Issue by phucdt1234** [ohitstom/spicetify-easyinstall#24]
"The ordinal 380 could not be located in the dynamic link library *\Spicetify-Easyinstall.exe."
After getting [this](https://github.com/ohitstom/spicetify-easyinstall/issues/21) error, i close and reopen the .exe file again and got this
![image](https://user-images.githubusercontent.com/77624484/164204652-9ea1a501-feac-44e1-a618-922fc5f8e3cf.png)

**Comment by ohitstom** [comment]
Thats a very odd error, have you tried redownloading incase something was corrupted?

**Comment by ohitstom** [comment]
closed due to inactivity

**Comment by phucdt1234** [comment]
I just try redownload the file and that error still pop up
