### ISSUE TITLE
Windows username with space

### ISSUE THREAD

**Issue by zhaobenny** [ohitstom/spicetify-easyinstall#25]
Looks like the program isn't happy with my Windows username with a space in it, and throws some errors or maybe its something else. 

<details>
<summary>Relevant logs</summary>

```
(6/10) Installing Spicetify...
MAKING FOLDER  C:\Users\Benny Zhao\spicetify-cli > OK
DOWNLOADING    https://github.com/spicetify/spicetify-cli/releases/download/v2.9.0/spicetify-2.9.0-windows-x64.zip > OK
EXTRACTING     C:\Users\Benny Zhao\spicetify-cli\spicetify-2.9.0-windows-x64.zip into C:\Users\Benny Zhao\spicetify-cli > OK
C:\Users\Benny : The term 'C:\Users\Benny' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
Traceback (most recent call last):
  File "modules\screens.py", line 203, in shownCallback
    await core.install(
  File "modules\core.py", line 153, in install
    prefs_check = utils.find_config_entry("prefs_path")
  File "modules\utils.py", line 49, in find_config_entry
    with open(config, 'rb') as filetemp: #Sanity
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Benny Zhao\\.spicetify\\config-xpui.ini'
```

</details>

**Comment by ohitstom** [comment]
Yup! This has been fixed in recent commits, unfortunately im not ready to release a new update for a while yet. If you want you can install python and use the source code thats more up to date! Sorry for the inconveniance!

**Comment by zhaobenny** [comment]
Hm, I gave the source code a go, had to bump PyQt5-sip to 12.10.1 as 12.10 didn't exist.

Some errors propped up in the install, did the block update action work properly? 

```
(7/10) Preventing Spotify from updating...
Invalid parameter "Zhao\AppData\Local\Spotify\Update"
Invalid parameter "Zhao\AppData\Local\Spotify\Update"
Finished blocking Spotify updates!
```

**Comment by ohitstom** [comment]
It may not have blocked updates properly i will look into that thank you, you can do it manually using these commands in admin cmd:

del %localappdata%\Spotify\Update

mkdir %localappdata%\Spotify\Update

icacls %localappdata%\Spotify\Update /deny "%username%":D

icacls %localappdata%\Spotify\Update /deny "%username%":R

**Comment by zhaobenny** [comment]
Thanks that worked! 🎉 

Had to enclose "%localappdata%\Spotify\Update" with quotes as that seemed to be the problem.

**Comment by ohitstom** [comment]
Interesting... Enjoy!

**Comment by lisbonjoker** [comment]
The windows release is still not working
