### ISSUE TITLE
File not found

### ISSUE THREAD

**Issue by notprash** [ohitstom/spicetify-easyinstall#26]
<img width="291" alt="image" src="https://user-images.githubusercontent.com/67903361/164706095-bf8f5799-8fcc-4710-8701-9ef453d5e5dd.png">

**Comment by ohitstom** [comment]
names with spaces are currently not supported due to a bug, refer to [https://github.com/ohitstom/spicetify-easyinstall/issues/25](#25)

**Comment by notprash** [comment]
when will this bug be fixed?

**Comment by ohitstom** [comment]
Its already fixed in the source code i just dont have enough features or time to get out a new update until school is over in a month or so.
