### ISSUE TITLE
could not find .exe file

### ISSUE THREAD

**Issue by fawnyeo** [ohitstom/spicetify-easyinstall#28]
Spicetify stopped working after upgrading to v.2.9.6. Got easyinstall to restart it but could not find .exe file 

**Screenshots**
![image](https://user-images.githubusercontent.com/102406279/164790979-0e3a3ec5-adab-492f-be60-d40cf17d6a16.png)

 - OS:  win11
 - Browser chrome
 - Version

**Comment by ohitstom** [comment]
Download from the releases page, check your antivirus isnt blocking and removing the exe, else install python 3.9.7 and remove the 'E:\Python\python-3.9.7\python.exe' part from the .bat and run it again.
