### ISSUE TITLE
spicetify not having a spicetify-cli folder

### ISSUE THREAD

**Issue by Expzr** [ohitstom/spicetify-easyinstall#32]
![image](https://user-images.githubusercontent.com/68577860/178135366-2aff608a-ae19-4173-8262-02009573944a.png)
after installing spotify and spicetify, it tries to install themes in spicetify-cli but the folder doesn't exist

**Comment by ohitstom** [comment]
Spicetify has had some path changes and I've yet to fully fix it, on holiday until tomorrow but I'll finish it and release it.
