### ISSUE TITLE
Something went wrong when installing with 3.0

### ISSUE THREAD

**Issue by ruudschouten** [ohitstom/spicetify-easyinstall#34]
**Describe the bug**
Trying to install Spicetify with version 3.0 doesn't work.
I tried it with both Admin rights and without, and both don't work for me.

**To Reproduce**

Without admin
1. Launch EasyInstall.
2. Click on 'Install'
3. Wait until step 5
4. ![python_2022-08-01_10-54-26](https://user-images.githubusercontent.com/1363911/182112717-9d44b70f-ed9c-40b0-8629-083266c808ef.png)

With admin
1. Launch EasyInstall.
2. Click on 'Install'
3. Wait until step 5
4. Spotify warns about how you shouldn't install with an admin account
5. Installer times out

**Expected behavior**
It should just install Spicetify

I was able to circumvent this error by running the installer with admin, and installing spotify myself, by running the installer downloaded in `temp` myself, right as the error from Spotify pops up telling me to not install it with admin.

**Comment by ohitstom** [comment]
It's likely because you've got it in programs dir, can you try installing it on say your desktop for me?

**Comment by ohitstom** [comment]
Please let me know how it went so i can progress this issue.

**Comment by ruudschouten** [comment]
I just tried installing it from my desktop, and that worked just fine

**Comment by ohitstom** [comment]
Awesome, sounds like a weird windows issue. I can possibly add conditionals and warn users in future, but i doubt this issue should affect many people.

Thanks for the response!
