### ISSUE TITLE
Error when installing

### ISSUE THREAD

**Issue by Metoku** [ohitstom/spicetify-easyinstall#40]
**Describe the bug**
I get an error while installing in step 4 of 13

**To Reproduce**
1. Install or update spicetify using this app
2. Once it reaches step 4 the error pops out

**Screenshots**
![image](https://user-images.githubusercontent.com/59681368/185921610-a86ece1e-039b-44b9-b5fa-8b778b4edd14.png)

**Desktop**
 - OS: Windows 10

**Comment by Metoku** [comment]
I have it download on a different drive where my OS is not installed. I am using an admin account

**Comment by ohitstom** [comment]
Could you possibly try moving it to your desktop for me? Deleting your
log.txt file from the directory and retrying the install?

**Comment by Metoku** [comment]
Thank you it worked for me. Appreciate the quick response and the work done.

**Comment by ohitstom** [comment]
Awesome! Sounds like a python quirk with how it handles os stuff, I'll look
into it but it might be something I can't fix for others!

Glad I could help ♥️
